name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: configure git identity
        run: |
          git config --global user.email "${GIT_CONFIG_USER_EMAIL}"
          git config --global user.name "${GIT_CONFIG_USER_NAME}"
      - name: install java with maven
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '25.0.1'
          java-package: 'jdk+fx'
          cache: 'maven'
      - name: import GPG key
        run: |
          echo "${OSSRH_GPG_PUBLIC_KEY}" | base64 -d | gpg --batch --import
          echo "${OSSRH_GPG_PRIVATE_KEY}" | base64 -d | gpg --batch --import
      - name: release maven artifact
        run: |
          ./mvnw -Pmaven-central-publishing,gpg-sign \
                 -Dstyle.color=always \
                 -s ./.mvn/settings.xml \
                 release:prepare \
                 release:perform \
                 -B -DskipTests=true -Djava.security.egd=file:/dev/./urandom -DscmCommentPrefix="[mvn-release] "
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GIT_CONFIG_USER_EMAIL: ${{ secrets.GIT_CONFIG_USER_EMAIL }}
      GIT_CONFIG_USER_NAME: ${{ secrets.GIT_CONFIG_USER_NAME }}
      MAVEN_GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
      MAVEN_GITHUB_PASSWORD: ${{ secrets.MAVEN_GITHUB_PASSWORD }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_TOKEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
      OSSRH_TOKEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
      OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      OSSRH_GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
      OSSRH_GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
