name: Build Test

run-name: ${{ github.actor }} is testing the project build

#on: [push]
on: [workflow_dispatch]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install java with maven
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '25.0.1'
          java-package: 'jdk+fx'
          cache: 'maven'
      - name: run `mvn package`
        run:
          ./mvnw -B package
